### ISSUE TITLE
Last version in docker won't work

### ISSUE THREAD

**Issue by DerTFL** [scragg0x/realms-wiki#180]
After the running docker
`docker run --name realms-wiki -p 5000:5000 -d realms/realms-wiki`
I have only a 500 error
Thanks!
Logs below:

```
docker logs realms-wiki
[2016-09-08 16:54:04 +0000] [8] [INFO] Starting gunicorn 19.3.0
[2016-09-08 16:54:04 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2016-09-08 16:54:04 +0000] [8] [INFO] Using worker: gevent
[2016-09-08 16:54:04 +0000] [13] [INFO] Booting worker with pid: 13
[2016-09-08 16:54:04 +0000] [16] [INFO] Booting worker with pid: 16
[2016-09-08 16:54:04 +0000] [19] [INFO] Booting worker with pid: 19
5.9.77.24 - - [08/Sep/2016:16:54:16 +0000] "GET / HTTP/1.1" 302 233 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"
[2016-09-08 16:54:17 +0000] [16] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 159, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/wiki/realms-wiki/realms/__init__.py", line 51, in __call__
    return super(Application, self).__call__(environ, start_response)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/home/wiki/realms-wiki/realms/__init__.py", line 161, in error_handler
    traceback=tb)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wiki/realms-wiki/realms/templates/errors/error.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/wiki/realms-wiki/realms/templates/layout.html", line 14, in top-level template code
    {% assets bundle %}
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 524, in _merge_and_apply
    kwargs=item_data)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/merge.py", line 276, in apply
    return self._wrap_cache(key, func)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/merge.py", line 218, in _wrap_cache
    content = func().getvalue()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/merge.py", line 251, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/filter/cleancss.py", line 37, in input
    self.subprocess(args, out, _in)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/webassets/filter/__init__.py", line 516, in subprocess
    raise FilterError('Program file not found: %s.' % argv[0])
FilterError: Program file not found: cleancss.
```

**Comment by gazpachoking** [comment]
I think this is a dupe of #171, and should be fixed by #175. Not exactly sure how docker works though, could it be pulling an old version from docker hub?

**Comment by Razzeee** [comment]
Problem is still valid. Last version on docker hub is from two month ago.

**Comment by dbio** [comment]
Seems like there is an updated version [here](https://hub.docker.com/r/scragg/realms-wiki/).
- Updated 9 days ago as of 13/01-2017

**Comment by Razzeee** [comment]
Funny, I just found that today.
